---

- name: Role agp_devspaces | Task workload | Enable tech preview features
  when: agp_devspaces_tech_preview_user_namespaces
  kubernetes.core.k8s:
    state: patched
    definition:
      apiVersion: config.openshift.io/v1
      kind: FeatureGate
      metadata:
        name: cluster
      spec:
        featureSet: CustomNoUpgrade
        customNoUpgrade:
          enabled:
            - ProcMountType
            - UserNamespacesSupport
            - UserNamespacesPodSecurityStandards

- name: Role agp_devspaces | Task workload | Create DevSpaces namespace
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ agp_devspaces_operator_devspaces_namespace }}"

- name: Role agp_devspaces | Task workload | Create custom SCC nested-podman-scc
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition: "{{ agp_devspaces_custom_nested_podman_scc }}"

- name: Role agp_devspaces | Task workload | Install OCP Devworkspace Operator
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ agp_devspaces_operator_devworkspace_name }}"
        namespace: "{{ agp_devspaces_operator_devworkspace_namespace }}"
        labels: "{{ agp_devspaces_operator_devworkspace_labels }}"
      spec:
        channel: "{{ agp_devspaces_operator_devworkspace_channel }}"
        installPlanApproval: "{{ agp_devspaces_operator_devworkspace_install_plan }}"
        name: "{{ agp_devspaces_operator_devworkspace_operator_name }}"
        source: "{{ agp_devspaces_operator_devworkspace_source }}"
        sourceNamespace: "{{ agp_devspaces_operator_devworkspace_source_namespace }}"
        startingCSV: "{{ agp_devspaces_operator_devworkspace_starting_csv }}"

- name: Role agp_devspaces | Task workload | Install OCP DevSpaces Subscription
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: "{{ agp_devspaces_operator_devspaces_name }}"
        namespace: "{{ agp_devspaces_operator_devspaces_namespace }}"
        labels: "{{ agp_devspaces_operator_devspaces_labels }}"
      spec:
        channel: "{{ agp_devspaces_operator_devspaces_channel }}"
        installPlanApproval: "{{ agp_devspaces_operator_devspaces_install_plan }}"
        name: "{{ agp_devspaces_operator_devspaces_operator_name }}"
        source: "{{ agp_devspaces_operator_devspaces_source }}"
        sourceNamespace: "{{ agp_devspaces_operator_devspaces_source_namespace }}"
        startingCSV: "{{ agp_devspaces_operator_devspaces_starting_csv }}"

- name: Role agp_devspaces | Task workload | Create CheCluster
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: org.eclipse.che/v2
      kind: CheCluster
      metadata:
        name: devspaces
        namespace: "{{ agp_devspaces_namespace }}"
      spec: "{{ agp_devspaces_che_cluster_spec }}"

- name: Role agp_devspaces | task workload | Deploy default workspace configurations
  when: agp_devspaces_default_workspace_config
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: vscode-editor-configurations
        namespace: "{{ agp_devspaces_namespace }}"
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: workspaces-config
      data:
        extensions.json: "{{ agp_devspaces_default_workspace_extensions_json }}"
        settings.json: "{{ agp_devspaces_default_workspace_settings_json }}"
        configurations.json: "{{ agp_devspaces_default_workspace_configurations_json }}"
